### ISSUE TITLE
About Us and Contacts Page information

### ISSUE THREAD

**Issue by ishankumar-ik** [MozUnicorn/MozUnicorn.github.io#6]
Kindly provide me with the information to be displayed over "About Us" page and "Contacts" page so that i could complete creating the pages.
Thank You

**Comment by shahbaz17** [comment]
**What is Unicorn Club ?**
Unicorn Club is well managed Tech Club of JNU , mainly
focuses on collaborative learning, team building and project
building. We strongly encourages learning of new
technologies.
We promote open-source technologies but it doesn't mean we
won't talk about closed source projects.

**Comment by shahbaz17** [comment]
https://wiki.mozilla.org/Unicorn_Club  - Wiki Page
mozunicornclub@gmail.com       - EMail
http://dev-jnu.slack.com/             - slack
https://www.facebook.com/groups/clubunicorn/ - Facebook
